// Code generated by go-swagger; DO NOT EDIT.

package d4c_registration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/crowdstrike/gofalcon/falcon/models"
)

// CreateD4CAWSAccountReader is a Reader for the CreateD4CAWSAccount structure.
type CreateD4CAWSAccountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateD4CAWSAccountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateD4CAWSAccountCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 207:
		result := NewCreateD4CAWSAccountMultiStatus()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateD4CAWSAccountBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewCreateD4CAWSAccountForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewCreateD4CAWSAccountTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewCreateD4CAWSAccountInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /cloud-connect-aws/entities/account/v2] CreateD4CAwsAccount", response, response.Code())
	}
}

// NewCreateD4CAWSAccountCreated creates a CreateD4CAWSAccountCreated with default headers values
func NewCreateD4CAWSAccountCreated() *CreateD4CAWSAccountCreated {
	return &CreateD4CAWSAccountCreated{}
}

/*
CreateD4CAWSAccountCreated describes a response with status code 201, with default header values.

Created
*/
type CreateD4CAWSAccountCreated struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.RegistrationAWSAccountResponseV2
}

// IsSuccess returns true when this create d4 c Aws account created response has a 2xx status code
func (o *CreateD4CAWSAccountCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create d4 c Aws account created response has a 3xx status code
func (o *CreateD4CAWSAccountCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create d4 c Aws account created response has a 4xx status code
func (o *CreateD4CAWSAccountCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this create d4 c Aws account created response has a 5xx status code
func (o *CreateD4CAWSAccountCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this create d4 c Aws account created response a status code equal to that given
func (o *CreateD4CAWSAccountCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the create d4 c Aws account created response
func (o *CreateD4CAWSAccountCreated) Code() int {
	return 201
}

func (o *CreateD4CAWSAccountCreated) Error() string {
	return fmt.Sprintf("[POST /cloud-connect-aws/entities/account/v2][%d] createD4CAwsAccountCreated  %+v", 201, o.Payload)
}

func (o *CreateD4CAWSAccountCreated) String() string {
	return fmt.Sprintf("[POST /cloud-connect-aws/entities/account/v2][%d] createD4CAwsAccountCreated  %+v", 201, o.Payload)
}

func (o *CreateD4CAWSAccountCreated) GetPayload() *models.RegistrationAWSAccountResponseV2 {
	return o.Payload
}

func (o *CreateD4CAWSAccountCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.RegistrationAWSAccountResponseV2)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateD4CAWSAccountMultiStatus creates a CreateD4CAWSAccountMultiStatus with default headers values
func NewCreateD4CAWSAccountMultiStatus() *CreateD4CAWSAccountMultiStatus {
	return &CreateD4CAWSAccountMultiStatus{}
}

/*
CreateD4CAWSAccountMultiStatus describes a response with status code 207, with default header values.

Multi-Status
*/
type CreateD4CAWSAccountMultiStatus struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.RegistrationAWSAccountResponseV2
}

// IsSuccess returns true when this create d4 c Aws account multi status response has a 2xx status code
func (o *CreateD4CAWSAccountMultiStatus) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this create d4 c Aws account multi status response has a 3xx status code
func (o *CreateD4CAWSAccountMultiStatus) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create d4 c Aws account multi status response has a 4xx status code
func (o *CreateD4CAWSAccountMultiStatus) IsClientError() bool {
	return false
}

// IsServerError returns true when this create d4 c Aws account multi status response has a 5xx status code
func (o *CreateD4CAWSAccountMultiStatus) IsServerError() bool {
	return false
}

// IsCode returns true when this create d4 c Aws account multi status response a status code equal to that given
func (o *CreateD4CAWSAccountMultiStatus) IsCode(code int) bool {
	return code == 207
}

// Code gets the status code for the create d4 c Aws account multi status response
func (o *CreateD4CAWSAccountMultiStatus) Code() int {
	return 207
}

func (o *CreateD4CAWSAccountMultiStatus) Error() string {
	return fmt.Sprintf("[POST /cloud-connect-aws/entities/account/v2][%d] createD4CAwsAccountMultiStatus  %+v", 207, o.Payload)
}

func (o *CreateD4CAWSAccountMultiStatus) String() string {
	return fmt.Sprintf("[POST /cloud-connect-aws/entities/account/v2][%d] createD4CAwsAccountMultiStatus  %+v", 207, o.Payload)
}

func (o *CreateD4CAWSAccountMultiStatus) GetPayload() *models.RegistrationAWSAccountResponseV2 {
	return o.Payload
}

func (o *CreateD4CAWSAccountMultiStatus) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.RegistrationAWSAccountResponseV2)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateD4CAWSAccountBadRequest creates a CreateD4CAWSAccountBadRequest with default headers values
func NewCreateD4CAWSAccountBadRequest() *CreateD4CAWSAccountBadRequest {
	return &CreateD4CAWSAccountBadRequest{}
}

/*
CreateD4CAWSAccountBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CreateD4CAWSAccountBadRequest struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.RegistrationAWSAccountResponseV2
}

// IsSuccess returns true when this create d4 c Aws account bad request response has a 2xx status code
func (o *CreateD4CAWSAccountBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create d4 c Aws account bad request response has a 3xx status code
func (o *CreateD4CAWSAccountBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create d4 c Aws account bad request response has a 4xx status code
func (o *CreateD4CAWSAccountBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this create d4 c Aws account bad request response has a 5xx status code
func (o *CreateD4CAWSAccountBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this create d4 c Aws account bad request response a status code equal to that given
func (o *CreateD4CAWSAccountBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the create d4 c Aws account bad request response
func (o *CreateD4CAWSAccountBadRequest) Code() int {
	return 400
}

func (o *CreateD4CAWSAccountBadRequest) Error() string {
	return fmt.Sprintf("[POST /cloud-connect-aws/entities/account/v2][%d] createD4CAwsAccountBadRequest  %+v", 400, o.Payload)
}

func (o *CreateD4CAWSAccountBadRequest) String() string {
	return fmt.Sprintf("[POST /cloud-connect-aws/entities/account/v2][%d] createD4CAwsAccountBadRequest  %+v", 400, o.Payload)
}

func (o *CreateD4CAWSAccountBadRequest) GetPayload() *models.RegistrationAWSAccountResponseV2 {
	return o.Payload
}

func (o *CreateD4CAWSAccountBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.RegistrationAWSAccountResponseV2)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateD4CAWSAccountForbidden creates a CreateD4CAWSAccountForbidden with default headers values
func NewCreateD4CAWSAccountForbidden() *CreateD4CAWSAccountForbidden {
	return &CreateD4CAWSAccountForbidden{}
}

/*
CreateD4CAWSAccountForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type CreateD4CAWSAccountForbidden struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this create d4 c Aws account forbidden response has a 2xx status code
func (o *CreateD4CAWSAccountForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create d4 c Aws account forbidden response has a 3xx status code
func (o *CreateD4CAWSAccountForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create d4 c Aws account forbidden response has a 4xx status code
func (o *CreateD4CAWSAccountForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this create d4 c Aws account forbidden response has a 5xx status code
func (o *CreateD4CAWSAccountForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this create d4 c Aws account forbidden response a status code equal to that given
func (o *CreateD4CAWSAccountForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the create d4 c Aws account forbidden response
func (o *CreateD4CAWSAccountForbidden) Code() int {
	return 403
}

func (o *CreateD4CAWSAccountForbidden) Error() string {
	return fmt.Sprintf("[POST /cloud-connect-aws/entities/account/v2][%d] createD4CAwsAccountForbidden  %+v", 403, o.Payload)
}

func (o *CreateD4CAWSAccountForbidden) String() string {
	return fmt.Sprintf("[POST /cloud-connect-aws/entities/account/v2][%d] createD4CAwsAccountForbidden  %+v", 403, o.Payload)
}

func (o *CreateD4CAWSAccountForbidden) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *CreateD4CAWSAccountForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateD4CAWSAccountTooManyRequests creates a CreateD4CAWSAccountTooManyRequests with default headers values
func NewCreateD4CAWSAccountTooManyRequests() *CreateD4CAWSAccountTooManyRequests {
	return &CreateD4CAWSAccountTooManyRequests{}
}

/*
CreateD4CAWSAccountTooManyRequests describes a response with status code 429, with default header values.

Too Many Requests
*/
type CreateD4CAWSAccountTooManyRequests struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	/* Too many requests, retry after this time (as milliseconds since epoch)
	 */
	XRateLimitRetryAfter int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this create d4 c Aws account too many requests response has a 2xx status code
func (o *CreateD4CAWSAccountTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create d4 c Aws account too many requests response has a 3xx status code
func (o *CreateD4CAWSAccountTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create d4 c Aws account too many requests response has a 4xx status code
func (o *CreateD4CAWSAccountTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this create d4 c Aws account too many requests response has a 5xx status code
func (o *CreateD4CAWSAccountTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this create d4 c Aws account too many requests response a status code equal to that given
func (o *CreateD4CAWSAccountTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the create d4 c Aws account too many requests response
func (o *CreateD4CAWSAccountTooManyRequests) Code() int {
	return 429
}

func (o *CreateD4CAWSAccountTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /cloud-connect-aws/entities/account/v2][%d] createD4CAwsAccountTooManyRequests  %+v", 429, o.Payload)
}

func (o *CreateD4CAWSAccountTooManyRequests) String() string {
	return fmt.Sprintf("[POST /cloud-connect-aws/entities/account/v2][%d] createD4CAwsAccountTooManyRequests  %+v", 429, o.Payload)
}

func (o *CreateD4CAWSAccountTooManyRequests) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *CreateD4CAWSAccountTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	// hydrates response header X-RateLimit-RetryAfter
	hdrXRateLimitRetryAfter := response.GetHeader("X-RateLimit-RetryAfter")

	if hdrXRateLimitRetryAfter != "" {
		valxRateLimitRetryAfter, err := swag.ConvertInt64(hdrXRateLimitRetryAfter)
		if err != nil {
			return errors.InvalidType("X-RateLimit-RetryAfter", "header", "int64", hdrXRateLimitRetryAfter)
		}
		o.XRateLimitRetryAfter = valxRateLimitRetryAfter
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateD4CAWSAccountInternalServerError creates a CreateD4CAWSAccountInternalServerError with default headers values
func NewCreateD4CAWSAccountInternalServerError() *CreateD4CAWSAccountInternalServerError {
	return &CreateD4CAWSAccountInternalServerError{}
}

/*
CreateD4CAWSAccountInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type CreateD4CAWSAccountInternalServerError struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.RegistrationAWSAccountResponseV2
}

// IsSuccess returns true when this create d4 c Aws account internal server error response has a 2xx status code
func (o *CreateD4CAWSAccountInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this create d4 c Aws account internal server error response has a 3xx status code
func (o *CreateD4CAWSAccountInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this create d4 c Aws account internal server error response has a 4xx status code
func (o *CreateD4CAWSAccountInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this create d4 c Aws account internal server error response has a 5xx status code
func (o *CreateD4CAWSAccountInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this create d4 c Aws account internal server error response a status code equal to that given
func (o *CreateD4CAWSAccountInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the create d4 c Aws account internal server error response
func (o *CreateD4CAWSAccountInternalServerError) Code() int {
	return 500
}

func (o *CreateD4CAWSAccountInternalServerError) Error() string {
	return fmt.Sprintf("[POST /cloud-connect-aws/entities/account/v2][%d] createD4CAwsAccountInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateD4CAWSAccountInternalServerError) String() string {
	return fmt.Sprintf("[POST /cloud-connect-aws/entities/account/v2][%d] createD4CAwsAccountInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateD4CAWSAccountInternalServerError) GetPayload() *models.RegistrationAWSAccountResponseV2 {
	return o.Payload
}

func (o *CreateD4CAWSAccountInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.RegistrationAWSAccountResponseV2)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
