// Code generated by go-swagger; DO NOT EDIT.

package d4c_registration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/crowdstrike/gofalcon/falcon/models"
)

// NewCreateD4CAWSAccountParams creates a new CreateD4CAWSAccountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateD4CAWSAccountParams() *CreateD4CAWSAccountParams {
	return &CreateD4CAWSAccountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateD4CAWSAccountParamsWithTimeout creates a new CreateD4CAWSAccountParams object
// with the ability to set a timeout on a request.
func NewCreateD4CAWSAccountParamsWithTimeout(timeout time.Duration) *CreateD4CAWSAccountParams {
	return &CreateD4CAWSAccountParams{
		timeout: timeout,
	}
}

// NewCreateD4CAWSAccountParamsWithContext creates a new CreateD4CAWSAccountParams object
// with the ability to set a context for a request.
func NewCreateD4CAWSAccountParamsWithContext(ctx context.Context) *CreateD4CAWSAccountParams {
	return &CreateD4CAWSAccountParams{
		Context: ctx,
	}
}

// NewCreateD4CAWSAccountParamsWithHTTPClient creates a new CreateD4CAWSAccountParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateD4CAWSAccountParamsWithHTTPClient(client *http.Client) *CreateD4CAWSAccountParams {
	return &CreateD4CAWSAccountParams{
		HTTPClient: client,
	}
}

/*
CreateD4CAWSAccountParams contains all the parameters to send to the API endpoint

	for the create d4 c Aws account operation.

	Typically these are written to a http.Request.
*/
type CreateD4CAWSAccountParams struct {

	// Body.
	Body *models.RegistrationAWSAccountCreateRequestD4CExtV2

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create d4 c Aws account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateD4CAWSAccountParams) WithDefaults() *CreateD4CAWSAccountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create d4 c Aws account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateD4CAWSAccountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create d4 c Aws account params
func (o *CreateD4CAWSAccountParams) WithTimeout(timeout time.Duration) *CreateD4CAWSAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create d4 c Aws account params
func (o *CreateD4CAWSAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create d4 c Aws account params
func (o *CreateD4CAWSAccountParams) WithContext(ctx context.Context) *CreateD4CAWSAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create d4 c Aws account params
func (o *CreateD4CAWSAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create d4 c Aws account params
func (o *CreateD4CAWSAccountParams) WithHTTPClient(client *http.Client) *CreateD4CAWSAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create d4 c Aws account params
func (o *CreateD4CAWSAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create d4 c Aws account params
func (o *CreateD4CAWSAccountParams) WithBody(body *models.RegistrationAWSAccountCreateRequestD4CExtV2) *CreateD4CAWSAccountParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create d4 c Aws account params
func (o *CreateD4CAWSAccountParams) SetBody(body *models.RegistrationAWSAccountCreateRequestD4CExtV2) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateD4CAWSAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
