// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// FwmgrDomainICMP fwmgr domain ICMP
//
// swagger:model fwmgr.domain.ICMP
type FwmgrDomainICMP struct {

	// icmp code
	// Required: true
	ICMPCode *string `json:"icmp_code"`

	// icmp type
	// Required: true
	ICMPType *string `json:"icmp_type"`
}

// Validate validates this fwmgr domain ICMP
func (m *FwmgrDomainICMP) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateICMPCode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateICMPType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FwmgrDomainICMP) validateICMPCode(formats strfmt.Registry) error {

	if err := validate.Required("icmp_code", "body", m.ICMPCode); err != nil {
		return err
	}

	return nil
}

func (m *FwmgrDomainICMP) validateICMPType(formats strfmt.Registry) error {

	if err := validate.Required("icmp_type", "body", m.ICMPType); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this fwmgr domain ICMP based on context it is used
func (m *FwmgrDomainICMP) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FwmgrDomainICMP) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FwmgrDomainICMP) UnmarshalBinary(b []byte) error {
	var res FwmgrDomainICMP
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
