// Code generated by go-swagger; DO NOT EDIT.

package cspm_registration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/crowdstrike/gofalcon/falcon/models"
)

// NewCreateCSPMAWSAccountParams creates a new CreateCSPMAWSAccountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCreateCSPMAWSAccountParams() *CreateCSPMAWSAccountParams {
	return &CreateCSPMAWSAccountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateCSPMAWSAccountParamsWithTimeout creates a new CreateCSPMAWSAccountParams object
// with the ability to set a timeout on a request.
func NewCreateCSPMAWSAccountParamsWithTimeout(timeout time.Duration) *CreateCSPMAWSAccountParams {
	return &CreateCSPMAWSAccountParams{
		timeout: timeout,
	}
}

// NewCreateCSPMAWSAccountParamsWithContext creates a new CreateCSPMAWSAccountParams object
// with the ability to set a context for a request.
func NewCreateCSPMAWSAccountParamsWithContext(ctx context.Context) *CreateCSPMAWSAccountParams {
	return &CreateCSPMAWSAccountParams{
		Context: ctx,
	}
}

// NewCreateCSPMAWSAccountParamsWithHTTPClient creates a new CreateCSPMAWSAccountParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateCSPMAWSAccountParamsWithHTTPClient(client *http.Client) *CreateCSPMAWSAccountParams {
	return &CreateCSPMAWSAccountParams{
		HTTPClient: client,
	}
}

/*
CreateCSPMAWSAccountParams contains all the parameters to send to the API endpoint

	for the create CSPM Aws account operation.

	Typically these are written to a http.Request.
*/
type CreateCSPMAWSAccountParams struct {

	// Body.
	Body *models.RegistrationAWSAccountCreateRequestExtV2

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create CSPM Aws account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateCSPMAWSAccountParams) WithDefaults() *CreateCSPMAWSAccountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create CSPM Aws account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CreateCSPMAWSAccountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create CSPM Aws account params
func (o *CreateCSPMAWSAccountParams) WithTimeout(timeout time.Duration) *CreateCSPMAWSAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create CSPM Aws account params
func (o *CreateCSPMAWSAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create CSPM Aws account params
func (o *CreateCSPMAWSAccountParams) WithContext(ctx context.Context) *CreateCSPMAWSAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create CSPM Aws account params
func (o *CreateCSPMAWSAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create CSPM Aws account params
func (o *CreateCSPMAWSAccountParams) WithHTTPClient(client *http.Client) *CreateCSPMAWSAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create CSPM Aws account params
func (o *CreateCSPMAWSAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create CSPM Aws account params
func (o *CreateCSPMAWSAccountParams) WithBody(body *models.RegistrationAWSAccountCreateRequestExtV2) *CreateCSPMAWSAccountParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create CSPM Aws account params
func (o *CreateCSPMAWSAccountParams) SetBody(body *models.RegistrationAWSAccountCreateRequestExtV2) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *CreateCSPMAWSAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
