// Code generated by go-swagger; DO NOT EDIT.

package cspm_registration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteCSPMAWSAccountParams creates a new DeleteCSPMAWSAccountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteCSPMAWSAccountParams() *DeleteCSPMAWSAccountParams {
	return &DeleteCSPMAWSAccountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteCSPMAWSAccountParamsWithTimeout creates a new DeleteCSPMAWSAccountParams object
// with the ability to set a timeout on a request.
func NewDeleteCSPMAWSAccountParamsWithTimeout(timeout time.Duration) *DeleteCSPMAWSAccountParams {
	return &DeleteCSPMAWSAccountParams{
		timeout: timeout,
	}
}

// NewDeleteCSPMAWSAccountParamsWithContext creates a new DeleteCSPMAWSAccountParams object
// with the ability to set a context for a request.
func NewDeleteCSPMAWSAccountParamsWithContext(ctx context.Context) *DeleteCSPMAWSAccountParams {
	return &DeleteCSPMAWSAccountParams{
		Context: ctx,
	}
}

// NewDeleteCSPMAWSAccountParamsWithHTTPClient creates a new DeleteCSPMAWSAccountParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteCSPMAWSAccountParamsWithHTTPClient(client *http.Client) *DeleteCSPMAWSAccountParams {
	return &DeleteCSPMAWSAccountParams{
		HTTPClient: client,
	}
}

/*
DeleteCSPMAWSAccountParams contains all the parameters to send to the API endpoint

	for the delete CSPM Aws account operation.

	Typically these are written to a http.Request.
*/
type DeleteCSPMAWSAccountParams struct {

	/* Ids.

	   AWS account IDs to remove
	*/
	Ids []string

	/* OrganizationIds.

	   AWS organization IDs to remove
	*/
	OrganizationIds []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete CSPM Aws account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteCSPMAWSAccountParams) WithDefaults() *DeleteCSPMAWSAccountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete CSPM Aws account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteCSPMAWSAccountParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete CSPM Aws account params
func (o *DeleteCSPMAWSAccountParams) WithTimeout(timeout time.Duration) *DeleteCSPMAWSAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete CSPM Aws account params
func (o *DeleteCSPMAWSAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete CSPM Aws account params
func (o *DeleteCSPMAWSAccountParams) WithContext(ctx context.Context) *DeleteCSPMAWSAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete CSPM Aws account params
func (o *DeleteCSPMAWSAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete CSPM Aws account params
func (o *DeleteCSPMAWSAccountParams) WithHTTPClient(client *http.Client) *DeleteCSPMAWSAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete CSPM Aws account params
func (o *DeleteCSPMAWSAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIds adds the ids to the delete CSPM Aws account params
func (o *DeleteCSPMAWSAccountParams) WithIds(ids []string) *DeleteCSPMAWSAccountParams {
	o.SetIds(ids)
	return o
}

// SetIds adds the ids to the delete CSPM Aws account params
func (o *DeleteCSPMAWSAccountParams) SetIds(ids []string) {
	o.Ids = ids
}

// WithOrganizationIds adds the organizationIds to the delete CSPM Aws account params
func (o *DeleteCSPMAWSAccountParams) WithOrganizationIds(organizationIds []string) *DeleteCSPMAWSAccountParams {
	o.SetOrganizationIds(organizationIds)
	return o
}

// SetOrganizationIds adds the organizationIds to the delete CSPM Aws account params
func (o *DeleteCSPMAWSAccountParams) SetOrganizationIds(organizationIds []string) {
	o.OrganizationIds = organizationIds
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteCSPMAWSAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Ids != nil {

		// binding items for ids
		joinedIds := o.bindParamIds(reg)

		// query array param ids
		if err := r.SetQueryParam("ids", joinedIds...); err != nil {
			return err
		}
	}

	if o.OrganizationIds != nil {

		// binding items for organization-ids
		joinedOrganizationIds := o.bindParamOrganizationIds(reg)

		// query array param organization-ids
		if err := r.SetQueryParam("organization-ids", joinedOrganizationIds...); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamDeleteCSPMAWSAccount binds the parameter ids
func (o *DeleteCSPMAWSAccountParams) bindParamIds(formats strfmt.Registry) []string {
	idsIR := o.Ids

	var idsIC []string
	for _, idsIIR := range idsIR { // explode []string

		idsIIV := idsIIR // string as string
		idsIC = append(idsIC, idsIIV)
	}

	// items.CollectionFormat: "multi"
	idsIS := swag.JoinByFormat(idsIC, "multi")

	return idsIS
}

// bindParamDeleteCSPMAWSAccount binds the parameter organization-ids
func (o *DeleteCSPMAWSAccountParams) bindParamOrganizationIds(formats strfmt.Registry) []string {
	organizationIdsIR := o.OrganizationIds

	var organizationIdsIC []string
	for _, organizationIdsIIR := range organizationIdsIR { // explode []string

		organizationIdsIIV := organizationIdsIIR // string as string
		organizationIdsIC = append(organizationIdsIC, organizationIdsIIV)
	}

	// items.CollectionFormat: "multi"
	organizationIdsIS := swag.JoinByFormat(organizationIdsIC, "multi")

	return organizationIdsIS
}
