// Code generated by go-swagger; DO NOT EDIT.

package cspm_registration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetCSPMAWSAccountParams creates a new GetCSPMAWSAccountParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCSPMAWSAccountParams() *GetCSPMAWSAccountParams {
	return &GetCSPMAWSAccountParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCSPMAWSAccountParamsWithTimeout creates a new GetCSPMAWSAccountParams object
// with the ability to set a timeout on a request.
func NewGetCSPMAWSAccountParamsWithTimeout(timeout time.Duration) *GetCSPMAWSAccountParams {
	return &GetCSPMAWSAccountParams{
		timeout: timeout,
	}
}

// NewGetCSPMAWSAccountParamsWithContext creates a new GetCSPMAWSAccountParams object
// with the ability to set a context for a request.
func NewGetCSPMAWSAccountParamsWithContext(ctx context.Context) *GetCSPMAWSAccountParams {
	return &GetCSPMAWSAccountParams{
		Context: ctx,
	}
}

// NewGetCSPMAWSAccountParamsWithHTTPClient creates a new GetCSPMAWSAccountParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCSPMAWSAccountParamsWithHTTPClient(client *http.Client) *GetCSPMAWSAccountParams {
	return &GetCSPMAWSAccountParams{
		HTTPClient: client,
	}
}

/*
GetCSPMAWSAccountParams contains all the parameters to send to the API endpoint

	for the get CSPM Aws account operation.

	Typically these are written to a http.Request.
*/
type GetCSPMAWSAccountParams struct {

	/* GroupBy.

	   Field to group by.
	*/
	GroupBy *string

	/* IamRoleArns.

	   AWS IAM role ARNs
	*/
	IamRoleArns []string

	/* Ids.

	   AWS account IDs
	*/
	Ids []string

	/* Limit.

	   The maximum records to return. Defaults to 100.

	   Default: 100
	*/
	Limit *int64

	/* Migrated.

	   Only return migrated d4c accounts
	*/
	Migrated *string

	/* Offset.

	   The offset to start retrieving records from
	*/
	Offset *int64

	/* OrganizationIds.

	   AWS organization IDs
	*/
	OrganizationIds []string

	/* ScanType.

	   Type of scan, dry or full, to perform on selected accounts
	*/
	ScanType *string

	/* Status.

	   Account status to filter results by.
	*/
	Status *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get CSPM Aws account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCSPMAWSAccountParams) WithDefaults() *GetCSPMAWSAccountParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get CSPM Aws account params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCSPMAWSAccountParams) SetDefaults() {
	var (
		limitDefault = int64(100)
	)

	val := GetCSPMAWSAccountParams{
		Limit: &limitDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get CSPM Aws account params
func (o *GetCSPMAWSAccountParams) WithTimeout(timeout time.Duration) *GetCSPMAWSAccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get CSPM Aws account params
func (o *GetCSPMAWSAccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get CSPM Aws account params
func (o *GetCSPMAWSAccountParams) WithContext(ctx context.Context) *GetCSPMAWSAccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get CSPM Aws account params
func (o *GetCSPMAWSAccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get CSPM Aws account params
func (o *GetCSPMAWSAccountParams) WithHTTPClient(client *http.Client) *GetCSPMAWSAccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get CSPM Aws account params
func (o *GetCSPMAWSAccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithGroupBy adds the groupBy to the get CSPM Aws account params
func (o *GetCSPMAWSAccountParams) WithGroupBy(groupBy *string) *GetCSPMAWSAccountParams {
	o.SetGroupBy(groupBy)
	return o
}

// SetGroupBy adds the groupBy to the get CSPM Aws account params
func (o *GetCSPMAWSAccountParams) SetGroupBy(groupBy *string) {
	o.GroupBy = groupBy
}

// WithIamRoleArns adds the iamRoleArns to the get CSPM Aws account params
func (o *GetCSPMAWSAccountParams) WithIamRoleArns(iamRoleArns []string) *GetCSPMAWSAccountParams {
	o.SetIamRoleArns(iamRoleArns)
	return o
}

// SetIamRoleArns adds the iamRoleArns to the get CSPM Aws account params
func (o *GetCSPMAWSAccountParams) SetIamRoleArns(iamRoleArns []string) {
	o.IamRoleArns = iamRoleArns
}

// WithIds adds the ids to the get CSPM Aws account params
func (o *GetCSPMAWSAccountParams) WithIds(ids []string) *GetCSPMAWSAccountParams {
	o.SetIds(ids)
	return o
}

// SetIds adds the ids to the get CSPM Aws account params
func (o *GetCSPMAWSAccountParams) SetIds(ids []string) {
	o.Ids = ids
}

// WithLimit adds the limit to the get CSPM Aws account params
func (o *GetCSPMAWSAccountParams) WithLimit(limit *int64) *GetCSPMAWSAccountParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get CSPM Aws account params
func (o *GetCSPMAWSAccountParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithMigrated adds the migrated to the get CSPM Aws account params
func (o *GetCSPMAWSAccountParams) WithMigrated(migrated *string) *GetCSPMAWSAccountParams {
	o.SetMigrated(migrated)
	return o
}

// SetMigrated adds the migrated to the get CSPM Aws account params
func (o *GetCSPMAWSAccountParams) SetMigrated(migrated *string) {
	o.Migrated = migrated
}

// WithOffset adds the offset to the get CSPM Aws account params
func (o *GetCSPMAWSAccountParams) WithOffset(offset *int64) *GetCSPMAWSAccountParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get CSPM Aws account params
func (o *GetCSPMAWSAccountParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithOrganizationIds adds the organizationIds to the get CSPM Aws account params
func (o *GetCSPMAWSAccountParams) WithOrganizationIds(organizationIds []string) *GetCSPMAWSAccountParams {
	o.SetOrganizationIds(organizationIds)
	return o
}

// SetOrganizationIds adds the organizationIds to the get CSPM Aws account params
func (o *GetCSPMAWSAccountParams) SetOrganizationIds(organizationIds []string) {
	o.OrganizationIds = organizationIds
}

// WithScanType adds the scanType to the get CSPM Aws account params
func (o *GetCSPMAWSAccountParams) WithScanType(scanType *string) *GetCSPMAWSAccountParams {
	o.SetScanType(scanType)
	return o
}

// SetScanType adds the scanType to the get CSPM Aws account params
func (o *GetCSPMAWSAccountParams) SetScanType(scanType *string) {
	o.ScanType = scanType
}

// WithStatus adds the status to the get CSPM Aws account params
func (o *GetCSPMAWSAccountParams) WithStatus(status *string) *GetCSPMAWSAccountParams {
	o.SetStatus(status)
	return o
}

// SetStatus adds the status to the get CSPM Aws account params
func (o *GetCSPMAWSAccountParams) SetStatus(status *string) {
	o.Status = status
}

// WriteToRequest writes these params to a swagger request
func (o *GetCSPMAWSAccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.GroupBy != nil {

		// query param group_by
		var qrGroupBy string

		if o.GroupBy != nil {
			qrGroupBy = *o.GroupBy
		}
		qGroupBy := qrGroupBy
		if qGroupBy != "" {

			if err := r.SetQueryParam("group_by", qGroupBy); err != nil {
				return err
			}
		}
	}

	if o.IamRoleArns != nil {

		// binding items for iam_role_arns
		joinedIamRoleArns := o.bindParamIamRoleArns(reg)

		// query array param iam_role_arns
		if err := r.SetQueryParam("iam_role_arns", joinedIamRoleArns...); err != nil {
			return err
		}
	}

	if o.Ids != nil {

		// binding items for ids
		joinedIds := o.bindParamIds(reg)

		// query array param ids
		if err := r.SetQueryParam("ids", joinedIds...); err != nil {
			return err
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Migrated != nil {

		// query param migrated
		var qrMigrated string

		if o.Migrated != nil {
			qrMigrated = *o.Migrated
		}
		qMigrated := qrMigrated
		if qMigrated != "" {

			if err := r.SetQueryParam("migrated", qMigrated); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if o.OrganizationIds != nil {

		// binding items for organization-ids
		joinedOrganizationIds := o.bindParamOrganizationIds(reg)

		// query array param organization-ids
		if err := r.SetQueryParam("organization-ids", joinedOrganizationIds...); err != nil {
			return err
		}
	}

	if o.ScanType != nil {

		// query param scan-type
		var qrScanType string

		if o.ScanType != nil {
			qrScanType = *o.ScanType
		}
		qScanType := qrScanType
		if qScanType != "" {

			if err := r.SetQueryParam("scan-type", qScanType); err != nil {
				return err
			}
		}
	}

	if o.Status != nil {

		// query param status
		var qrStatus string

		if o.Status != nil {
			qrStatus = *o.Status
		}
		qStatus := qrStatus
		if qStatus != "" {

			if err := r.SetQueryParam("status", qStatus); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamGetCSPMAWSAccount binds the parameter iam_role_arns
func (o *GetCSPMAWSAccountParams) bindParamIamRoleArns(formats strfmt.Registry) []string {
	iamRoleArnsIR := o.IamRoleArns

	var iamRoleArnsIC []string
	for _, iamRoleArnsIIR := range iamRoleArnsIR { // explode []string

		iamRoleArnsIIV := iamRoleArnsIIR // string as string
		iamRoleArnsIC = append(iamRoleArnsIC, iamRoleArnsIIV)
	}

	// items.CollectionFormat: "multi"
	iamRoleArnsIS := swag.JoinByFormat(iamRoleArnsIC, "multi")

	return iamRoleArnsIS
}

// bindParamGetCSPMAWSAccount binds the parameter ids
func (o *GetCSPMAWSAccountParams) bindParamIds(formats strfmt.Registry) []string {
	idsIR := o.Ids

	var idsIC []string
	for _, idsIIR := range idsIR { // explode []string

		idsIIV := idsIIR // string as string
		idsIC = append(idsIC, idsIIV)
	}

	// items.CollectionFormat: "multi"
	idsIS := swag.JoinByFormat(idsIC, "multi")

	return idsIS
}

// bindParamGetCSPMAWSAccount binds the parameter organization-ids
func (o *GetCSPMAWSAccountParams) bindParamOrganizationIds(formats strfmt.Registry) []string {
	organizationIdsIR := o.OrganizationIds

	var organizationIdsIC []string
	for _, organizationIdsIIR := range organizationIdsIR { // explode []string

		organizationIdsIIV := organizationIdsIIR // string as string
		organizationIdsIC = append(organizationIdsIC, organizationIdsIIV)
	}

	// items.CollectionFormat: "multi"
	organizationIdsIS := swag.JoinByFormat(organizationIdsIC, "multi")

	return organizationIdsIS
}
