// Code generated by go-swagger; DO NOT EDIT.

package cspm_registration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetCSPMAWSConsoleSetupURLsParams creates a new GetCSPMAWSConsoleSetupURLsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetCSPMAWSConsoleSetupURLsParams() *GetCSPMAWSConsoleSetupURLsParams {
	return &GetCSPMAWSConsoleSetupURLsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetCSPMAWSConsoleSetupURLsParamsWithTimeout creates a new GetCSPMAWSConsoleSetupURLsParams object
// with the ability to set a timeout on a request.
func NewGetCSPMAWSConsoleSetupURLsParamsWithTimeout(timeout time.Duration) *GetCSPMAWSConsoleSetupURLsParams {
	return &GetCSPMAWSConsoleSetupURLsParams{
		timeout: timeout,
	}
}

// NewGetCSPMAWSConsoleSetupURLsParamsWithContext creates a new GetCSPMAWSConsoleSetupURLsParams object
// with the ability to set a context for a request.
func NewGetCSPMAWSConsoleSetupURLsParamsWithContext(ctx context.Context) *GetCSPMAWSConsoleSetupURLsParams {
	return &GetCSPMAWSConsoleSetupURLsParams{
		Context: ctx,
	}
}

// NewGetCSPMAWSConsoleSetupURLsParamsWithHTTPClient creates a new GetCSPMAWSConsoleSetupURLsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetCSPMAWSConsoleSetupURLsParamsWithHTTPClient(client *http.Client) *GetCSPMAWSConsoleSetupURLsParams {
	return &GetCSPMAWSConsoleSetupURLsParams{
		HTTPClient: client,
	}
}

/*
GetCSPMAWSConsoleSetupURLsParams contains all the parameters to send to the API endpoint

	for the get CSPM Aws console setup u r ls operation.

	Typically these are written to a http.Request.
*/
type GetCSPMAWSConsoleSetupURLsParams struct {

	/* Ids.

	   AWS account IDs
	*/
	Ids []string

	/* Region.

	   Region
	*/
	Region *string

	// UseExistingCloudtrail.
	UseExistingCloudtrail *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get CSPM Aws console setup u r ls params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCSPMAWSConsoleSetupURLsParams) WithDefaults() *GetCSPMAWSConsoleSetupURLsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get CSPM Aws console setup u r ls params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetCSPMAWSConsoleSetupURLsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get CSPM Aws console setup u r ls params
func (o *GetCSPMAWSConsoleSetupURLsParams) WithTimeout(timeout time.Duration) *GetCSPMAWSConsoleSetupURLsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get CSPM Aws console setup u r ls params
func (o *GetCSPMAWSConsoleSetupURLsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get CSPM Aws console setup u r ls params
func (o *GetCSPMAWSConsoleSetupURLsParams) WithContext(ctx context.Context) *GetCSPMAWSConsoleSetupURLsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get CSPM Aws console setup u r ls params
func (o *GetCSPMAWSConsoleSetupURLsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get CSPM Aws console setup u r ls params
func (o *GetCSPMAWSConsoleSetupURLsParams) WithHTTPClient(client *http.Client) *GetCSPMAWSConsoleSetupURLsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get CSPM Aws console setup u r ls params
func (o *GetCSPMAWSConsoleSetupURLsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIds adds the ids to the get CSPM Aws console setup u r ls params
func (o *GetCSPMAWSConsoleSetupURLsParams) WithIds(ids []string) *GetCSPMAWSConsoleSetupURLsParams {
	o.SetIds(ids)
	return o
}

// SetIds adds the ids to the get CSPM Aws console setup u r ls params
func (o *GetCSPMAWSConsoleSetupURLsParams) SetIds(ids []string) {
	o.Ids = ids
}

// WithRegion adds the region to the get CSPM Aws console setup u r ls params
func (o *GetCSPMAWSConsoleSetupURLsParams) WithRegion(region *string) *GetCSPMAWSConsoleSetupURLsParams {
	o.SetRegion(region)
	return o
}

// SetRegion adds the region to the get CSPM Aws console setup u r ls params
func (o *GetCSPMAWSConsoleSetupURLsParams) SetRegion(region *string) {
	o.Region = region
}

// WithUseExistingCloudtrail adds the useExistingCloudtrail to the get CSPM Aws console setup u r ls params
func (o *GetCSPMAWSConsoleSetupURLsParams) WithUseExistingCloudtrail(useExistingCloudtrail *string) *GetCSPMAWSConsoleSetupURLsParams {
	o.SetUseExistingCloudtrail(useExistingCloudtrail)
	return o
}

// SetUseExistingCloudtrail adds the useExistingCloudtrail to the get CSPM Aws console setup u r ls params
func (o *GetCSPMAWSConsoleSetupURLsParams) SetUseExistingCloudtrail(useExistingCloudtrail *string) {
	o.UseExistingCloudtrail = useExistingCloudtrail
}

// WriteToRequest writes these params to a swagger request
func (o *GetCSPMAWSConsoleSetupURLsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Ids != nil {

		// binding items for ids
		joinedIds := o.bindParamIds(reg)

		// query array param ids
		if err := r.SetQueryParam("ids", joinedIds...); err != nil {
			return err
		}
	}

	if o.Region != nil {

		// query param region
		var qrRegion string

		if o.Region != nil {
			qrRegion = *o.Region
		}
		qRegion := qrRegion
		if qRegion != "" {

			if err := r.SetQueryParam("region", qRegion); err != nil {
				return err
			}
		}
	}

	if o.UseExistingCloudtrail != nil {

		// query param use_existing_cloudtrail
		var qrUseExistingCloudtrail string

		if o.UseExistingCloudtrail != nil {
			qrUseExistingCloudtrail = *o.UseExistingCloudtrail
		}
		qUseExistingCloudtrail := qrUseExistingCloudtrail
		if qUseExistingCloudtrail != "" {

			if err := r.SetQueryParam("use_existing_cloudtrail", qUseExistingCloudtrail); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamGetCSPMAWSConsoleSetupURLs binds the parameter ids
func (o *GetCSPMAWSConsoleSetupURLsParams) bindParamIds(formats strfmt.Registry) []string {
	idsIR := o.Ids

	var idsIC []string
	for _, idsIIR := range idsIR { // explode []string

		idsIIV := idsIIR // string as string
		idsIC = append(idsIC, idsIIV)
	}

	// items.CollectionFormat: "multi"
	idsIS := swag.JoinByFormat(idsIC, "multi")

	return idsIS
}
