// Code generated by go-swagger; DO NOT EDIT.

package intel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetMITREReportParams creates a new GetMITREReportParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMITREReportParams() *GetMITREReportParams {
	return &GetMITREReportParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMITREReportParamsWithTimeout creates a new GetMITREReportParams object
// with the ability to set a timeout on a request.
func NewGetMITREReportParamsWithTimeout(timeout time.Duration) *GetMITREReportParams {
	return &GetMITREReportParams{
		timeout: timeout,
	}
}

// NewGetMITREReportParamsWithContext creates a new GetMITREReportParams object
// with the ability to set a context for a request.
func NewGetMITREReportParamsWithContext(ctx context.Context) *GetMITREReportParams {
	return &GetMITREReportParams{
		Context: ctx,
	}
}

// NewGetMITREReportParamsWithHTTPClient creates a new GetMITREReportParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMITREReportParamsWithHTTPClient(client *http.Client) *GetMITREReportParams {
	return &GetMITREReportParams{
		HTTPClient: client,
	}
}

/*
GetMITREReportParams contains all the parameters to send to the API endpoint

	for the get Mitre report operation.

	Typically these are written to a http.Request.
*/
type GetMITREReportParams struct {

	/* ActorID.

	   Actor ID(derived from the actor's name)
	*/
	ActorID string

	/* Format.

	   Supported report formats: CSV or JSON
	*/
	Format string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get Mitre report params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMITREReportParams) WithDefaults() *GetMITREReportParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get Mitre report params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMITREReportParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get Mitre report params
func (o *GetMITREReportParams) WithTimeout(timeout time.Duration) *GetMITREReportParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get Mitre report params
func (o *GetMITREReportParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get Mitre report params
func (o *GetMITREReportParams) WithContext(ctx context.Context) *GetMITREReportParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get Mitre report params
func (o *GetMITREReportParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get Mitre report params
func (o *GetMITREReportParams) WithHTTPClient(client *http.Client) *GetMITREReportParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get Mitre report params
func (o *GetMITREReportParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithActorID adds the actorID to the get Mitre report params
func (o *GetMITREReportParams) WithActorID(actorID string) *GetMITREReportParams {
	o.SetActorID(actorID)
	return o
}

// SetActorID adds the actorId to the get Mitre report params
func (o *GetMITREReportParams) SetActorID(actorID string) {
	o.ActorID = actorID
}

// WithFormat adds the format to the get Mitre report params
func (o *GetMITREReportParams) WithFormat(format string) *GetMITREReportParams {
	o.SetFormat(format)
	return o
}

// SetFormat adds the format to the get Mitre report params
func (o *GetMITREReportParams) SetFormat(format string) {
	o.Format = format
}

// WriteToRequest writes these params to a swagger request
func (o *GetMITREReportParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param actor_id
	qrActorID := o.ActorID
	qActorID := qrActorID
	if qActorID != "" {

		if err := r.SetQueryParam("actor_id", qActorID); err != nil {
			return err
		}
	}

	// query param format
	qrFormat := o.Format
	qFormat := qrFormat
	if qFormat != "" {

		if err := r.SetQueryParam("format", qFormat); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
