// Code generated by go-swagger; DO NOT EDIT.

package intel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/crowdstrike/gofalcon/falcon/models"
)

// GetMITREReportReader is a Reader for the GetMITREReport structure.
type GetMITREReportReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMITREReportReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetMITREReportOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetMITREReportForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewGetMITREReportTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /intel/entities/mitre-reports/v1] GetMitreReport", response, response.Code())
	}
}

// NewGetMITREReportOK creates a GetMITREReportOK with default headers values
func NewGetMITREReportOK() *GetMITREReportOK {
	return &GetMITREReportOK{}
}

/*
GetMITREReportOK describes a response with status code 200, with default header values.

OK
*/
type GetMITREReportOK struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64
}

// IsSuccess returns true when this get Mitre report o k response has a 2xx status code
func (o *GetMITREReportOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Mitre report o k response has a 3xx status code
func (o *GetMITREReportOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Mitre report o k response has a 4xx status code
func (o *GetMITREReportOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Mitre report o k response has a 5xx status code
func (o *GetMITREReportOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Mitre report o k response a status code equal to that given
func (o *GetMITREReportOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Mitre report o k response
func (o *GetMITREReportOK) Code() int {
	return 200
}

func (o *GetMITREReportOK) Error() string {
	return fmt.Sprintf("[GET /intel/entities/mitre-reports/v1][%d] getMitreReportOK ", 200)
}

func (o *GetMITREReportOK) String() string {
	return fmt.Sprintf("[GET /intel/entities/mitre-reports/v1][%d] getMitreReportOK ", 200)
}

func (o *GetMITREReportOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	return nil
}

// NewGetMITREReportForbidden creates a GetMITREReportForbidden with default headers values
func NewGetMITREReportForbidden() *GetMITREReportForbidden {
	return &GetMITREReportForbidden{}
}

/*
GetMITREReportForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetMITREReportForbidden struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this get Mitre report forbidden response has a 2xx status code
func (o *GetMITREReportForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Mitre report forbidden response has a 3xx status code
func (o *GetMITREReportForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Mitre report forbidden response has a 4xx status code
func (o *GetMITREReportForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Mitre report forbidden response has a 5xx status code
func (o *GetMITREReportForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get Mitre report forbidden response a status code equal to that given
func (o *GetMITREReportForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get Mitre report forbidden response
func (o *GetMITREReportForbidden) Code() int {
	return 403
}

func (o *GetMITREReportForbidden) Error() string {
	return fmt.Sprintf("[GET /intel/entities/mitre-reports/v1][%d] getMitreReportForbidden  %+v", 403, o.Payload)
}

func (o *GetMITREReportForbidden) String() string {
	return fmt.Sprintf("[GET /intel/entities/mitre-reports/v1][%d] getMitreReportForbidden  %+v", 403, o.Payload)
}

func (o *GetMITREReportForbidden) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *GetMITREReportForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMITREReportTooManyRequests creates a GetMITREReportTooManyRequests with default headers values
func NewGetMITREReportTooManyRequests() *GetMITREReportTooManyRequests {
	return &GetMITREReportTooManyRequests{}
}

/*
GetMITREReportTooManyRequests describes a response with status code 429, with default header values.

Too Many Requests
*/
type GetMITREReportTooManyRequests struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	/* Too many requests, retry after this time (as milliseconds since epoch)
	 */
	XRateLimitRetryAfter int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this get Mitre report too many requests response has a 2xx status code
func (o *GetMITREReportTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Mitre report too many requests response has a 3xx status code
func (o *GetMITREReportTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Mitre report too many requests response has a 4xx status code
func (o *GetMITREReportTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Mitre report too many requests response has a 5xx status code
func (o *GetMITREReportTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this get Mitre report too many requests response a status code equal to that given
func (o *GetMITREReportTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the get Mitre report too many requests response
func (o *GetMITREReportTooManyRequests) Code() int {
	return 429
}

func (o *GetMITREReportTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /intel/entities/mitre-reports/v1][%d] getMitreReportTooManyRequests  %+v", 429, o.Payload)
}

func (o *GetMITREReportTooManyRequests) String() string {
	return fmt.Sprintf("[GET /intel/entities/mitre-reports/v1][%d] getMitreReportTooManyRequests  %+v", 429, o.Payload)
}

func (o *GetMITREReportTooManyRequests) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *GetMITREReportTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	// hydrates response header X-RateLimit-RetryAfter
	hdrXRateLimitRetryAfter := response.GetHeader("X-RateLimit-RetryAfter")

	if hdrXRateLimitRetryAfter != "" {
		valxRateLimitRetryAfter, err := swag.ConvertInt64(hdrXRateLimitRetryAfter)
		if err != nil {
			return errors.InvalidType("X-RateLimit-RetryAfter", "header", "int64", hdrXRateLimitRetryAfter)
		}
		o.XRateLimitRetryAfter = valxRateLimitRetryAfter
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
