// Code generated by go-swagger; DO NOT EDIT.

package intel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewQueryMITREAttacksParams creates a new QueryMITREAttacksParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewQueryMITREAttacksParams() *QueryMITREAttacksParams {
	return &QueryMITREAttacksParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewQueryMITREAttacksParamsWithTimeout creates a new QueryMITREAttacksParams object
// with the ability to set a timeout on a request.
func NewQueryMITREAttacksParamsWithTimeout(timeout time.Duration) *QueryMITREAttacksParams {
	return &QueryMITREAttacksParams{
		timeout: timeout,
	}
}

// NewQueryMITREAttacksParamsWithContext creates a new QueryMITREAttacksParams object
// with the ability to set a context for a request.
func NewQueryMITREAttacksParamsWithContext(ctx context.Context) *QueryMITREAttacksParams {
	return &QueryMITREAttacksParams{
		Context: ctx,
	}
}

// NewQueryMITREAttacksParamsWithHTTPClient creates a new QueryMITREAttacksParams object
// with the ability to set a custom HTTPClient for a request.
func NewQueryMITREAttacksParamsWithHTTPClient(client *http.Client) *QueryMITREAttacksParams {
	return &QueryMITREAttacksParams{
		HTTPClient: client,
	}
}

/*
QueryMITREAttacksParams contains all the parameters to send to the API endpoint

	for the query Mitre attacks operation.

	Typically these are written to a http.Request.
*/
type QueryMITREAttacksParams struct {

	/* ID.

	   The actor ID(derived from the actor's name) for which to retrieve a list of attacks, for example: fancy-bear.
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the query Mitre attacks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QueryMITREAttacksParams) WithDefaults() *QueryMITREAttacksParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the query Mitre attacks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QueryMITREAttacksParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the query Mitre attacks params
func (o *QueryMITREAttacksParams) WithTimeout(timeout time.Duration) *QueryMITREAttacksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the query Mitre attacks params
func (o *QueryMITREAttacksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the query Mitre attacks params
func (o *QueryMITREAttacksParams) WithContext(ctx context.Context) *QueryMITREAttacksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the query Mitre attacks params
func (o *QueryMITREAttacksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the query Mitre attacks params
func (o *QueryMITREAttacksParams) WithHTTPClient(client *http.Client) *QueryMITREAttacksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the query Mitre attacks params
func (o *QueryMITREAttacksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the query Mitre attacks params
func (o *QueryMITREAttacksParams) WithID(id string) *QueryMITREAttacksParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the query Mitre attacks params
func (o *QueryMITREAttacksParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *QueryMITREAttacksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param id
	qrID := o.ID
	qID := qrID
	if qID != "" {

		if err := r.SetQueryParam("id", qID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
