// Code generated by go-swagger; DO NOT EDIT.

package intel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/crowdstrike/gofalcon/falcon/models"
)

// QueryMITREAttacksReader is a Reader for the QueryMITREAttacks structure.
type QueryMITREAttacksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *QueryMITREAttacksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewQueryMITREAttacksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewQueryMITREAttacksForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewQueryMITREAttacksTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /intel/queries/mitre/v1] QueryMitreAttacks", response, response.Code())
	}
}

// NewQueryMITREAttacksOK creates a QueryMITREAttacksOK with default headers values
func NewQueryMITREAttacksOK() *QueryMITREAttacksOK {
	return &QueryMITREAttacksOK{}
}

/*
QueryMITREAttacksOK describes a response with status code 200, with default header values.

OK
*/
type QueryMITREAttacksOK struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.DomainQueryMITREAttacksResponse
}

// IsSuccess returns true when this query Mitre attacks o k response has a 2xx status code
func (o *QueryMITREAttacksOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this query Mitre attacks o k response has a 3xx status code
func (o *QueryMITREAttacksOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this query Mitre attacks o k response has a 4xx status code
func (o *QueryMITREAttacksOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this query Mitre attacks o k response has a 5xx status code
func (o *QueryMITREAttacksOK) IsServerError() bool {
	return false
}

// IsCode returns true when this query Mitre attacks o k response a status code equal to that given
func (o *QueryMITREAttacksOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the query Mitre attacks o k response
func (o *QueryMITREAttacksOK) Code() int {
	return 200
}

func (o *QueryMITREAttacksOK) Error() string {
	return fmt.Sprintf("[GET /intel/queries/mitre/v1][%d] queryMitreAttacksOK  %+v", 200, o.Payload)
}

func (o *QueryMITREAttacksOK) String() string {
	return fmt.Sprintf("[GET /intel/queries/mitre/v1][%d] queryMitreAttacksOK  %+v", 200, o.Payload)
}

func (o *QueryMITREAttacksOK) GetPayload() *models.DomainQueryMITREAttacksResponse {
	return o.Payload
}

func (o *QueryMITREAttacksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.DomainQueryMITREAttacksResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQueryMITREAttacksForbidden creates a QueryMITREAttacksForbidden with default headers values
func NewQueryMITREAttacksForbidden() *QueryMITREAttacksForbidden {
	return &QueryMITREAttacksForbidden{}
}

/*
QueryMITREAttacksForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type QueryMITREAttacksForbidden struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this query Mitre attacks forbidden response has a 2xx status code
func (o *QueryMITREAttacksForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this query Mitre attacks forbidden response has a 3xx status code
func (o *QueryMITREAttacksForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this query Mitre attacks forbidden response has a 4xx status code
func (o *QueryMITREAttacksForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this query Mitre attacks forbidden response has a 5xx status code
func (o *QueryMITREAttacksForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this query Mitre attacks forbidden response a status code equal to that given
func (o *QueryMITREAttacksForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the query Mitre attacks forbidden response
func (o *QueryMITREAttacksForbidden) Code() int {
	return 403
}

func (o *QueryMITREAttacksForbidden) Error() string {
	return fmt.Sprintf("[GET /intel/queries/mitre/v1][%d] queryMitreAttacksForbidden  %+v", 403, o.Payload)
}

func (o *QueryMITREAttacksForbidden) String() string {
	return fmt.Sprintf("[GET /intel/queries/mitre/v1][%d] queryMitreAttacksForbidden  %+v", 403, o.Payload)
}

func (o *QueryMITREAttacksForbidden) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *QueryMITREAttacksForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQueryMITREAttacksTooManyRequests creates a QueryMITREAttacksTooManyRequests with default headers values
func NewQueryMITREAttacksTooManyRequests() *QueryMITREAttacksTooManyRequests {
	return &QueryMITREAttacksTooManyRequests{}
}

/*
QueryMITREAttacksTooManyRequests describes a response with status code 429, with default header values.

Too Many Requests
*/
type QueryMITREAttacksTooManyRequests struct {

	/* Trace-ID: submit to support if resolving an issue
	 */
	XCSTRACEID string

	/* Request limit per minute.
	 */
	XRateLimitLimit int64

	/* The number of requests remaining for the sliding one minute window.
	 */
	XRateLimitRemaining int64

	/* Too many requests, retry after this time (as milliseconds since epoch)
	 */
	XRateLimitRetryAfter int64

	Payload *models.MsaReplyMetaOnly
}

// IsSuccess returns true when this query Mitre attacks too many requests response has a 2xx status code
func (o *QueryMITREAttacksTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this query Mitre attacks too many requests response has a 3xx status code
func (o *QueryMITREAttacksTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this query Mitre attacks too many requests response has a 4xx status code
func (o *QueryMITREAttacksTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this query Mitre attacks too many requests response has a 5xx status code
func (o *QueryMITREAttacksTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this query Mitre attacks too many requests response a status code equal to that given
func (o *QueryMITREAttacksTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the query Mitre attacks too many requests response
func (o *QueryMITREAttacksTooManyRequests) Code() int {
	return 429
}

func (o *QueryMITREAttacksTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /intel/queries/mitre/v1][%d] queryMitreAttacksTooManyRequests  %+v", 429, o.Payload)
}

func (o *QueryMITREAttacksTooManyRequests) String() string {
	return fmt.Sprintf("[GET /intel/queries/mitre/v1][%d] queryMitreAttacksTooManyRequests  %+v", 429, o.Payload)
}

func (o *QueryMITREAttacksTooManyRequests) GetPayload() *models.MsaReplyMetaOnly {
	return o.Payload
}

func (o *QueryMITREAttacksTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header X-CS-TRACEID
	hdrXCSTRACEID := response.GetHeader("X-CS-TRACEID")

	if hdrXCSTRACEID != "" {
		o.XCSTRACEID = hdrXCSTRACEID
	}

	// hydrates response header X-RateLimit-Limit
	hdrXRateLimitLimit := response.GetHeader("X-RateLimit-Limit")

	if hdrXRateLimitLimit != "" {
		valxRateLimitLimit, err := swag.ConvertInt64(hdrXRateLimitLimit)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Limit", "header", "int64", hdrXRateLimitLimit)
		}
		o.XRateLimitLimit = valxRateLimitLimit
	}

	// hydrates response header X-RateLimit-Remaining
	hdrXRateLimitRemaining := response.GetHeader("X-RateLimit-Remaining")

	if hdrXRateLimitRemaining != "" {
		valxRateLimitRemaining, err := swag.ConvertInt64(hdrXRateLimitRemaining)
		if err != nil {
			return errors.InvalidType("X-RateLimit-Remaining", "header", "int64", hdrXRateLimitRemaining)
		}
		o.XRateLimitRemaining = valxRateLimitRemaining
	}

	// hydrates response header X-RateLimit-RetryAfter
	hdrXRateLimitRetryAfter := response.GetHeader("X-RateLimit-RetryAfter")

	if hdrXRateLimitRetryAfter != "" {
		valxRateLimitRetryAfter, err := swag.ConvertInt64(hdrXRateLimitRetryAfter)
		if err != nil {
			return errors.InvalidType("X-RateLimit-RetryAfter", "header", "int64", hdrXRateLimitRetryAfter)
		}
		o.XRateLimitRetryAfter = valxRateLimitRetryAfter
	}

	o.Payload = new(models.MsaReplyMetaOnly)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
