// Code generated by go-swagger; DO NOT EDIT.

package ioc

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewIOCTypeQueryV1Params creates a new IOCTypeQueryV1Params object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewIOCTypeQueryV1Params() *IOCTypeQueryV1Params {
	return &IOCTypeQueryV1Params{
		timeout: cr.DefaultTimeout,
	}
}

// NewIOCTypeQueryV1ParamsWithTimeout creates a new IOCTypeQueryV1Params object
// with the ability to set a timeout on a request.
func NewIOCTypeQueryV1ParamsWithTimeout(timeout time.Duration) *IOCTypeQueryV1Params {
	return &IOCTypeQueryV1Params{
		timeout: timeout,
	}
}

// NewIOCTypeQueryV1ParamsWithContext creates a new IOCTypeQueryV1Params object
// with the ability to set a context for a request.
func NewIOCTypeQueryV1ParamsWithContext(ctx context.Context) *IOCTypeQueryV1Params {
	return &IOCTypeQueryV1Params{
		Context: ctx,
	}
}

// NewIOCTypeQueryV1ParamsWithHTTPClient creates a new IOCTypeQueryV1Params object
// with the ability to set a custom HTTPClient for a request.
func NewIOCTypeQueryV1ParamsWithHTTPClient(client *http.Client) *IOCTypeQueryV1Params {
	return &IOCTypeQueryV1Params{
		HTTPClient: client,
	}
}

/*
IOCTypeQueryV1Params contains all the parameters to send to the API endpoint

	for the ioc type query v1 operation.

	Typically these are written to a http.Request.
*/
type IOCTypeQueryV1Params struct {

	/* Limit.

	   Number of ids to return.
	*/
	Limit *int64

	/* Offset.

	   Starting index of overall result set from which to return ids.
	*/
	Offset *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the ioc type query v1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IOCTypeQueryV1Params) WithDefaults() *IOCTypeQueryV1Params {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the ioc type query v1 params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *IOCTypeQueryV1Params) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the ioc type query v1 params
func (o *IOCTypeQueryV1Params) WithTimeout(timeout time.Duration) *IOCTypeQueryV1Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the ioc type query v1 params
func (o *IOCTypeQueryV1Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the ioc type query v1 params
func (o *IOCTypeQueryV1Params) WithContext(ctx context.Context) *IOCTypeQueryV1Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the ioc type query v1 params
func (o *IOCTypeQueryV1Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the ioc type query v1 params
func (o *IOCTypeQueryV1Params) WithHTTPClient(client *http.Client) *IOCTypeQueryV1Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the ioc type query v1 params
func (o *IOCTypeQueryV1Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the ioc type query v1 params
func (o *IOCTypeQueryV1Params) WithLimit(limit *int64) *IOCTypeQueryV1Params {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the ioc type query v1 params
func (o *IOCTypeQueryV1Params) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the ioc type query v1 params
func (o *IOCTypeQueryV1Params) WithOffset(offset *string) *IOCTypeQueryV1Params {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the ioc type query v1 params
func (o *IOCTypeQueryV1Params) SetOffset(offset *string) {
	o.Offset = offset
}

// WriteToRequest writes these params to a swagger request
func (o *IOCTypeQueryV1Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset string

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := qrOffset
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
